services:
  - type: web
    name: synapse-pms
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
