services:
  - type: web
    name: synapse-pms
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
